### ISSUE TITLE
Issues when building d1-pac due to yanked dependency

### ISSUE THREAD

**Issue by jspngh** [duskmoon314/aw-pac#28]
A [number of versions](https://crates.io/crates/riscv/versions) of the `riscv` crate have been yanked, causing issues when building the `d1-pac`.

The dependency versions should be updated to `riscv = "0.10.1"` and `riscv-rt = "0.11.0"`.
Will the renovate bot do this automatically, or should I create a pull request for this?

**Comment by duskmoon314** [comment]
Oh, thanks for reminding me.

I just triggered renovate. I will release 0.0.31 with the deps updated.

**Comment by duskmoon314** [comment]
Done

v0.0.31 is released to solve the problem: riscv and riscv-rt are updated

**Comment by jspngh** [comment]
Thanks a lot!
