### ISSUE TITLE
SVD - D1 v1.0 manual

### ISSUE THREAD

**Issue by kassane** [duskmoon314/aw-pac#7]
Hi @duskmoon314

Google recently recommended this project to me when I was looking for the SVD allwinner D1.
I tried to do the same in relation to the manual v1.0 D1-H but had a [issue] during the extraction.
Do you have a script to extract the manual or is there another way?

[issue]: https://github.com/daym/allwinner-register-interface-extractor/issues/1

**Comment by duskmoon314** [comment]
I have taken a look at the issue and that is great work! To be honest, the svd in this project is just information copied from the pdf and reshaped via the regex expression. 😢 

It seems that you have managed to generate a complete svd of D1-H. Do you have an interest in contributing to this project?

**Comment by kassane** [comment]
> I have taken a look at the issue and that is great work! To be honest, the svd in this project is just information copied from the pdf and reshaped via the regex expression. 😢 

Thanks.

> It seems that you have managed to generate a complete svd of D1-H. Do you have an interest in contributing to this project?

Well, I suggest using the files attached to this issue. Then I'll try to generate D1s SVD and give you the copy.

- https://github.com/ZigEmbeddedGroup/regz/issues/17#issuecomment-1115330029

**Comment by kassane** [comment]
Hi @duskmoon314 

I uploaded all the SVDs in the zig issue mentioned above and noticed that there are already updates in `d1-pac`.

If it's already resolved, close this issue, otherwise I'll do a comparison on the SVDs and send PR.
